import { test, expect, type Page } from '@playwright/test';
const password = process.env.E2E_PASSWORD!;
const origin = process.env.E2E_BASE_URL!;
async function owner(page: Page) {
 await page.goto('/login');
 await expect(page.getByText('Сессия завершена или недействительна. Войдите снова.')).toHaveCount(0);
 await page.getByLabel('Логин', { exact: true }).fill('owner');
 await page.getByLabel('Пароль', { exact: true }).fill(password);
 await page.getByLabel('Пароль', { exact: true }).press('Tab');
 await expect(page.getByRole('button', { name: 'Войти', exact: true })).toBeFocused();
 await page.keyboard.press('Enter');
 await expect(page.getByRole('heading', { name: 'Наш круг' })).toBeVisible();
}
test('editor preserves failed draft, supports Unicode, editing and keyboard deletion', async ({ page }) => {
 await owner(page);
 await page.getByRole('link', { name: /Новый пост/ }).click();
 await page.getByRole('button', { name: 'Опубликовать', exact: true }).click();
 await expect(page.getByRole('alert')).toContainText('Добавьте текст');
 await page.getByLabel('Текст публикации').fill('🙂'.repeat(5001));
 await expect(page.getByText('5001 / 5000 символов')).toBeVisible();
 await page.getByRole('button', { name: 'Опубликовать', exact: true }).click();
 await expect(page.getByRole('alert')).toContainText('до 5000');
 const draft = 'Черновик сохранится при ошибке. <script>alert(1)</script>';
 await page.getByLabel('Текст публикации').fill(draft);
 await page.route('**/api/v1/posts', async route => {
  if (route.request().method() === 'POST') await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { code: 'UNAVAILABLE', message: 'Временно недоступно' } }) });
  else await route.continue();
 });
 await page.getByRole('button', { name: 'Опубликовать', exact: true }).click();
 await expect(page.getByRole('alert')).toContainText('Временно недоступно');
 await expect(page.getByLabel('Текст публикации')).toHaveValue(draft);
 await page.unroute('**/api/v1/posts');
 await page.getByRole('button', { name: 'Опубликовать', exact: true }).click();
 await expect(page.locator('article .post-body')).toHaveText(draft);
 expect(await page.locator('article script').count()).toBe(0);
 await page.getByRole('link', { name: 'Изменить', exact: true }).click();
 await page.getByLabel('Текст публикации').fill('Теперь исправлено');
 await page.getByRole('button', { name: 'Сохранить изменения', exact: true }).click();
 await expect(page.locator('article .post-body')).toHaveText('Теперь исправлено');
 const postID = page.url().split('/').at(-1)!;
 await page.getByRole('button', { name: 'Удалить', exact: true }).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await expect(page.getByRole('button', { name: 'Отмена', exact: true })).toBeFocused();
 await page.keyboard.press('Escape');
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.getByRole('button', { name: 'Удалить', exact: true })).toBeFocused();
 await page.keyboard.press('Enter');
 await page.getByRole('dialog').getByRole('button', { name: 'Удалить', exact: true }).click();
 await expect(page.getByRole('heading', { name: 'Наш круг' })).toBeVisible();
 expect((await page.request.get(`/api/v1/posts/${postID}`)).status()).toBe(404);
});
test('mobile owner navigation and password change complete in browser', async ({ page, browser }) => {
 await page.setViewportSize({ width: 360, height: 800 });
 await owner(page);
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 await page.getByRole('link', { name: 'Приглашения', exact: true }).click();
 await expect(page.getByRole('heading', { name: 'Приглашения', exact: true })).toBeVisible();
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 const invitation = await (await page.request.post('/api/v1/admin/invites', { headers: { Origin: origin } })).json();
 const context = await browser.newContext();
 const friend = await context.newPage(); await friend.goto(invitation.url);
 await friend.getByLabel('Логин', { exact: true }).fill('password_test');
 await friend.getByLabel('Отображаемое имя', { exact: true }).fill('Тест пароля');
 await friend.getByLabel('Пароль', { exact: true }).fill(password);
 await friend.getByRole('button', { name: 'Присоединиться' }).click();
 await expect(friend.getByRole('heading', { name: 'Наш круг' })).toBeVisible();
 await friend.getByRole('link', { name: 'Профиль', exact: true }).click();
 await friend.getByLabel('Текущий пароль', { exact: true }).fill(password);
 await friend.getByLabel('Новый пароль', { exact: true }).fill(password + '-new');
 await friend.getByLabel('Повторите новый пароль', { exact: true }).fill(password + '-new');
 await friend.getByRole('button', { name: 'Изменить пароль', exact: true }).click();
 await expect(friend.getByRole('heading', { name: 'Войти в SweetNet' })).toBeVisible();
 await friend.getByLabel('Логин', { exact: true }).fill('password_test');
 await friend.getByLabel('Пароль', { exact: true }).fill(password + '-new');
 await friend.getByRole('button', { name: 'Войти', exact: true }).click();
 await expect(friend.getByRole('heading', { name: 'Наш круг' })).toBeVisible();
 await context.close();
});
